server:
    port: 8083
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: admin
        url: jdbc:h2:mem:testdb
        username: admin
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
